version: '3.7'

services:

  php:
    build:
      context: ./php
      args:
        - UID_DOCKER=${UID_DOCKER}
        - GID_DOCKER=${GID_DOCKER}
    restart: always
    volumes:
      - ./php/www.conf:/usr/local/etc/php-fpm.d/zz-www.conf
      - ./php/php.ini:/usr/local/etc/php/conf.d/20-default.ini
      - ${PROJECT_PATH}:/var/www/html
    expose:
      - 9000

  nginx:
    build:
      context: ./nginx
      args:
        - DOMAIN=${DOMAIN}
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/ssl:/var/www/ssl
      - ./logs:/var/log/nginx
      - ${PROJECT_PATH}:/var/www/html
